export type Language = 'en' | 'ru' | 'kk'

const copy = {
  en: { home:'Home', growth:'Growth', path:'Path', events:'Events', ai:'AI', next:'Your next step', seeAll:'See all', why:'Why this?', add:'Add to plan', complete:'Mark completed', required:'Required', forYou:'For you', explore:'Explore', how:'How is this calculated?', readiness:'readiness', requirements:'requirements met', critical:'critical gaps', rhythm:'Your rhythm', assessed:'Assessed', estimate:'Since review', target:'Target', recent:'Recent evidence', logout:'Sign out', noData:'Nothing to show yet.', retry:'Try again', notForMe:'Not for me', blocked:'Catalog opportunity gap', loading:'Loading your career path…' },
  ru: { home:'Главная', growth:'Рост', path:'Путь', events:'События', ai:'AI', next:'Ваш следующий шаг', seeAll:'Все', why:'Почему?', add:'Добавить в план', complete:'Отметить завершённым', required:'Обязательно', forYou:'Для вас', explore:'Обзор', how:'Как это рассчитано?', readiness:'готовность', requirements:'требований выполнено', critical:'критических пробела', rhythm:'Ваш ритм', assessed:'Оценка', estimate:'После оценки', target:'Цель', recent:'Недавние подтверждения', logout:'Выйти', noData:'Пока нечего показывать.', retry:'Повторить', notForMe:'Не подходит', blocked:'Пробел каталога', loading:'Загружаем карьерный путь…' },
  kk: { home:'Басты бет', growth:'Өсу', path:'Жол', events:'Іс-шаралар', ai:'AI', next:'Келесі қадамыңыз', seeAll:'Барлығы', why:'Неліктен?', add:'Жоспарға қосу', complete:'Аяқталды деп белгілеу', required:'Міндетті', forYou:'Сіз үшін', explore:'Шолу', how:'Бұл қалай есептелді?', readiness:'дайындық', requirements:'талап орындалды', critical:'сыни олқылық', rhythm:'Сіздің ырғағыңыз', assessed:'Бағаланған', estimate:'Шолудан кейін', target:'Мақсат', recent:'Соңғы дәлелдер', logout:'Шығу', noData:'Әзірге көрсететін ештеңе жоқ.', retry:'Қайталау', notForMe:'Маған сай емес', blocked:'Каталог мүмкіндігінің олқылығы', loading:'Мансап жолы жүктелуде…' },
} as const

export function t(language: Language, key: keyof typeof copy.en): string { return copy[language][key] }
