export type Language = 'en' | 'ru' | 'kk'

const copy = {
  en: {
    home:'Home', growth:'Growth', path:'Path', events:'Events', ai:'AI', next:'Your next step', seeAll:'See all', why:'Why this?', add:'Add to plan', complete:'Mark completed', required:'Required', forYou:'For you', explore:'Explore', how:'How is this calculated?', readiness:'readiness', requirements:'requirements met', critical:'critical gaps', rhythm:'Your rhythm', assessed:'Assessed', estimate:'Since review', target:'Target', recent:'Recent evidence', logout:'Sign out', noData:'Nothing to show yet.', retry:'Try again', notForMe:'Not for me', blocked:'Catalog opportunity gap', loading:'Loading your career path…',
    hello:'Hello', buildingToward:'Building toward', of:'of', you:'you', whyReady:'Why am I this ready?', rhythmNote:'Light weeks are normal. This shows direction, not attendance.',
    myGrowth:'My Growth', toward:'Toward', updated:'Just updated from your completed activity.', sinceReviewEstimate:'Since review estimate', skillBySkill:'Skill by skill', criticalLabel:'critical', sinceReview:'since review', estimateLabel:'estimate', targetLabel:'target', noEvidence:'No post-review evidence yet.', evidenceNote:'Activities move the estimate. The formal level changes only at reassessment.',
    careerPath:'Career Path', yourTarget:'Your target', ready:'ready', youAreHere:'You are here', since:'since', toReach:'To reach', now:'now', noCatalogStep:'no catalog step', met:'met',
    search:'Search events or skills', exploreEmpty:'Every currently eligible activity is ranked in “For you”. Complete or dismiss one to refresh your next steps.', noRequired:'No required activities are due.', open:'Open', due:'due', updating:'Updating',
    aiSubtitle:'Structured from your target, skills and history', aiQuestion:'What should I focus on next?', whyAnswer:'Why this answer?', whyAnswerDetail:'Your target, numbered gaps, activity evidence, format and effort are used. No private data or hidden profile is used.', openSkill:'Open skill', openPath:'Open career path',
    whatChanged:'What changed', formalUnchanged:'estimate · formal level unchanged', careerReadiness:'Career readiness', seeChanged:'See what changed', readinessDetail:'Each target skill contributes up to its required level. Partial progress counts; activity gains remain an estimate until reassessment.', flexible:'Flexible', skillGaps:'Skill gaps', show:'Show', hide:'Hide'
  },
  ru: {
    home:'Главная', growth:'Рост', path:'Путь', events:'События', ai:'AI', next:'Ваш следующий шаг', seeAll:'Все', why:'Почему?', add:'Добавить в план', complete:'Отметить завершённым', required:'Обязательно', forYou:'Для вас', explore:'Обзор', how:'Как это рассчитано?', readiness:'готовность', requirements:'требований выполнено', critical:'критических пробела', rhythm:'Ваш ритм', assessed:'Оценка', estimate:'После оценки', target:'Цель', recent:'Недавние подтверждения', logout:'Выйти', noData:'Пока нечего показывать.', retry:'Повторить', notForMe:'Не подходит', blocked:'Пробел каталога', loading:'Загружаем карьерный путь…',
    hello:'Здравствуйте', buildingToward:'Движение к позиции', of:'из', you:'вы здесь', whyReady:'Почему у меня такая готовность?', rhythmNote:'Спокойные недели — это нормально. Здесь показано направление, а не посещаемость.',
    myGrowth:'Мой рост', toward:'Цель', updated:'Данные обновлены после завершённой активности.', sinceReviewEstimate:'Оценка после ревью', skillBySkill:'Навыки подробно', criticalLabel:'критический', sinceReview:'после ревью', estimateLabel:'оценка', targetLabel:'цель', noEvidence:'После ревью пока нет новых подтверждений.', evidenceNote:'Активности меняют предварительную оценку. Формальный уровень обновляется только после переоценки.',
    careerPath:'Карьерный путь', yourTarget:'Ваша цель', ready:'готовность', youAreHere:'Вы здесь', since:'с', toReach:'Чтобы достичь', now:'сейчас', noCatalogStep:'нет подходящей активности', met:'достигнуто',
    search:'Поиск событий или навыков', exploreEmpty:'Все доступные активности ранжированы во вкладке «Для вас». Завершите или скройте вариант, чтобы обновить рекомендации.', noRequired:'Нет обязательных активностей с текущим сроком.', open:'Открыть', due:'срок', updating:'Обновление',
    aiSubtitle:'Ответ на основе вашей цели, навыков и истории', aiQuestion:'На чём мне сосредоточиться дальше?', whyAnswer:'Почему такой ответ?', whyAnswerDetail:'Учитываются ваша цель, разрывы навыков, подтверждения активностей, формат и нагрузка. Личные данные и скрытые профили не используются.', openSkill:'Открыть навык', openPath:'Открыть карьерный путь',
    whatChanged:'Что изменилось', formalUnchanged:'предварительно · формальный уровень не изменён', careerReadiness:'Карьерная готовность', seeChanged:'Посмотреть изменения', readinessDetail:'Каждый целевой навык учитывается до требуемого уровня. Частичный прогресс засчитывается, а прирост от активностей остаётся предварительным до переоценки.', flexible:'Гибкий график', skillGaps:'Пробелы навыков', show:'Показать', hide:'Скрыть'
  },
  kk: {
    home:'Басты бет', growth:'Өсу', path:'Жол', events:'Іс-шаралар', ai:'AI', next:'Келесі қадамыңыз', seeAll:'Барлығы', why:'Неліктен?', add:'Жоспарға қосу', complete:'Аяқталды деп белгілеу', required:'Міндетті', forYou:'Сіз үшін', explore:'Шолу', how:'Бұл қалай есептелді?', readiness:'дайындық', requirements:'талап орындалды', critical:'сыни олқылық', rhythm:'Сіздің ырғағыңыз', assessed:'Бағаланған', estimate:'Шолудан кейін', target:'Мақсат', recent:'Соңғы дәлелдер', logout:'Шығу', noData:'Әзірге көрсететін ештеңе жоқ.', retry:'Қайталау', notForMe:'Маған сай емес', blocked:'Каталог мүмкіндігінің олқылығы', loading:'Мансап жолы жүктелуде…',
    hello:'Сәлем', buildingToward:'Келесі мақсат', of:'ішінен', you:'сіз осындасыз', whyReady:'Неліктен менің дайындығым осындай?', rhythmNote:'Баяу апталар қалыпты. Бұл қатысуды емес, бағытты көрсетеді.',
    myGrowth:'Менің өсуім', toward:'Мақсат', updated:'Аяқталған іс-шарадан кейін деректер жаңартылды.', sinceReviewEstimate:'Шолудан кейінгі баға', skillBySkill:'Дағдылар бойынша', criticalLabel:'сыни', sinceReview:'шолудан кейін', estimateLabel:'баға', targetLabel:'мақсат', noEvidence:'Шолудан кейін жаңа дәлел әлі жоқ.', evidenceNote:'Іс-шаралар болжамды бағаны өзгертеді. Ресми деңгей тек қайта бағалаудан кейін жаңартылады.',
    careerPath:'Мансап жолы', yourTarget:'Сіздің мақсатыңыз', ready:'дайын', youAreHere:'Сіз осындасыз', since:'бастап', toReach:'Жету үшін', now:'қазір', noCatalogStep:'сәйкес іс-шара жоқ', met:'орындалды',
    search:'Іс-шара немесе дағды іздеу', exploreEmpty:'Барлық қолжетімді іс-шара «Сіз үшін» бөлімінде реттелген. Ұсыныстарды жаңарту үшін біреуін аяқтаңыз немесе жасырыңыз.', noRequired:'Мерзімі келген міндетті іс-шара жоқ.', open:'Ашу', due:'мерзімі', updating:'Жаңарту',
    aiSubtitle:'Мақсат, дағдылар және тарих негізіндегі жауап', aiQuestion:'Келесіде неге көңіл бөлуім керек?', whyAnswer:'Неліктен бұл жауап?', whyAnswerDetail:'Мақсат, дағды алшақтықтары, іс-шара дәлелдері, формат және күш есепке алынады. Жеке деректер мен жасырын профиль қолданылмайды.', openSkill:'Дағдыны ашу', openPath:'Мансап жолын ашу',
    whatChanged:'Не өзгерді', formalUnchanged:'болжам · ресми деңгей өзгерген жоқ', careerReadiness:'Мансаптық дайындық', seeChanged:'Өзгерістерді көру', readinessDetail:'Әр мақсатты дағды қажетті деңгейге дейін есептеледі. Ішінара прогресс ескеріледі, ал іс-шара өсімі қайта бағалауға дейін болжам болып қалады.', flexible:'Икемді уақыт', skillGaps:'Дағды олқылықтары', show:'Көрсету', hide:'Жасыру'
  },
} as const

export function t(language: Language, key: keyof typeof copy.en): string { return copy[language][key] }

const labels: Record<Language, Record<string,string>> = {
  en: {},
  ru: { 'Strong match':'Отличное совпадение', 'Good match':'Хорошее совпадение', Exploratory:'Для изучения', mentoring:'наставничество', workshop:'воркшоп', course:'курс', meetup:'встреча', compliance:'обязательный курс', onboarding:'адаптация', certification:'сертификация', online:'онлайн', offline:'очно', hybrid:'гибридно', self_paced:'самостоятельно' },
  kk: { 'Strong match':'Өте жақсы сәйкестік', 'Good match':'Жақсы сәйкестік', Exploratory:'Зерттеуге арналған', mentoring:'тәлімгерлік', workshop:'воркшоп', course:'курс', meetup:'кездесу', compliance:'міндетті курс', onboarding:'бейімдеу', certification:'сертификаттау', online:'онлайн', offline:'офлайн', hybrid:'аралас', self_paced:'өз бетінше' },
}

export function localizeLabel(language:Language,value:string):string { return labels[language][value]||value.replaceAll('_',' ') }
